from pyvis.network import Network

pyvis_graph = Network()

pyvis_graph.add_node(0, label="ahead", color="Yellow", size=5)
pyvis_graph.add_node(1, label="go", color="Blue", size=15)
pyvis_graph.add_node(2, label="alone", color="Red", size=5)
pyvis_graph.add_node(3, label="leave", color="Green", size=5)
pyvis_graph.add_node(4, label="hole", color="Black", size=10)
pyvis_graph.add_node(5, label="fuck", color="Orange", size=55)
pyvis_graph.add_node(6, label="ass", color="Brown", size=45)
pyvis_graph.add_node(7, label="attacks", color="Ivory", size=5)
pyvis_graph.add_node(8, label="personal", color="Teal", size=5)
pyvis_graph.add_node(9, label="bull", color="Silver", size=5)
pyvis_graph.add_node(10, label="shit", color="Purple", size=30)
pyvis_graph.add_node(11, label="unsigned", color="Navy blue", size=5)
pyvis_graph.add_node(12, label="comment", color="Pea green", size=5)
pyvis_graph.add_node(13, label="ed", color="Gray", size=5)
pyvis_graph.add_node(14, label="retard", color="Maroon", size=5)
pyvis_graph.add_node(15, label="mother", color="Charcoal", size=5)
pyvis_graph.add_node(16, label="ual", color="Aquamarine", size=10)
pyvis_graph.add_node(17, label="sex", color="Coral", size=15)
pyvis_graph.add_node(18, label="homo", color="Fuchsia", size=15)
pyvis_graph.add_node(19, label="org", color="Wheat", size=10)
pyvis_graph.add_node(20, label="http", color="Lime", size=5)
pyvis_graph.add_node(21, label="wikipedia", color="Crimson", size=15)
pyvis_graph.add_node(22, label="ing", color="Khaki", size=5)
pyvis_graph.add_node(23, label="suck", color="Hot pink", size=20)
pyvis_graph.add_node(24, label="piece", color="Magenta", size=5)
pyvis_graph.add_node(25, label="bitch", color="Olden", size=5)
pyvis_graph.add_node(26, label="get", color="Plum", size=5)
pyvis_graph.add_node(27, label="like", color="Olive", size=5)
pyvis_graph.add_node(28, label="cock", color="Cyan", size=5)
pyvis_graph.add_node(29, label="cunt", color="Yellow", size=5)
pyvis_graph.add_node(30, label="dick", color="Blue", size=5)
pyvis_graph.add_node(31, label="edit", color="Red", size=5)
pyvis_graph.add_node(32, label="page", color="Green", size=10)
pyvis_graph.add_node(33, label="talk", color="Black", size=5)
pyvis_graph.add_edge(18, 17, size=10, color="Purple")
pyvis_graph.add_edge(17, 18, size=10, color="Navy blue")
pyvis_graph.add_edge(29, 5, size=10, color="Pea green")
pyvis_graph.add_edge(19, 21, size=10, color="Gray")
pyvis_graph.add_edge(5, 10, size=10, color="Maroon")
pyvis_graph.add_edge(7, 8, size=10, color="Charcoal")
pyvis_graph.add_edge(16, 18, size=10, color="Aquamarine")
pyvis_graph.add_edge(15, 5, size=10, color="Coral")
pyvis_graph.add_edge(4, 5, size=10, color="Fuchsia")
pyvis_graph.add_edge(2, 3, size=10, color="Wheat")
pyvis_graph.add_edge(30, 5, size=10, color="Lime")
pyvis_graph.add_edge(24, 10, size=10, color="Crimson")
pyvis_graph.add_edge(31, 32, size=10, color="Khaki")
pyvis_graph.add_edge(0, 1, size=10, color="Hot pink")
pyvis_graph.add_edge(5, 6, size=10, color="Magenta")
pyvis_graph.add_edge(27, 6, size=10, color="Olden")
pyvis_graph.add_edge(23, 6, size=10, color="Plum")
pyvis_graph.add_edge(33, 32, size=10, color="Olive")
pyvis_graph.add_edge(26, 6, size=10, color="Cyan")
pyvis_graph.add_edge(19, 20, size=10, color="Yellow")
pyvis_graph.add_edge(9, 10, size=10, color="Blue")
pyvis_graph.add_edge(4, 6, size=10, color="Red")
pyvis_graph.add_edge(1, 5, size=10, color="Green")
pyvis_graph.add_edge(22, 23, size=10, color="Black")
pyvis_graph.add_edge(28, 23, size=10, color="Orange")
pyvis_graph.add_edge(10, 6, size=10, color="Brown")
pyvis_graph.add_edge(16, 17, size=10, color="Ivory")
pyvis_graph.add_edge(11, 12, size=10, color="Teal")
pyvis_graph.add_edge(21, 10, size=10, color="Silver")
pyvis_graph.add_edge(13, 14, size=10, color="Purple")
pyvis_graph.add_edge(5, 23, size=10, color="Navy blue")
pyvis_graph.add_edge(10, 5, size=10, color="Pea green")
pyvis_graph.add_edge(1, 6, size=10, color="Gray")
pyvis_graph.add_edge(6, 5, size=10, color="Maroon")
pyvis_graph.add_edge(25, 5, size=10, color="Charcoal")
pyvis_graph.add_edge(21, 6, size=10, color="Aquamarine")
pyvis_graph.force_atlas_2based()
pyvis_graph.show("tmp.fig02.html")